general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follow_focus: false

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: true

  # Whether to show floating windows as always on top.
  show_floating_on_top: false

  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "false"

gaps:
  # Gap between adjacent windows.
  inner_gap: "5px"

  # Gap between windows and the screen edge.
  outer_gap: "10px"

# Highlight active/inactive windows with a colored border.
# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: "#0000ff"

  inactive:
    enabled: false
    color: "#ff0000"

bar:
  height: "25px"
  position: "top"
  opacity: 0.7
  background: "#20242cc4"
  foreground: "#ffffff"
  font_family: "Segoe UI"
  font_size: "13px"
  padding: "4px 6px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"
  components_center:
    - type: "window title"
  components_right:
    - type: "cpu"
      label: "🤖 {percent_usage}%  "
      refresh_interval_ms: 1000
    - type: "memory"
      label: "📂 {percent_usage}%  "
      refresh_interval_ms: 1000
    - type: "volume"
      label_low: "🔉{volume_level}%"
      label_medium: "🔉{volume_level}%"
      label_high: "🔊{volume_level}%"
      label_mute: "🔇{volume_level}%"
    - type: "tiling direction"
      label_horizontal: ">"
      label_vertical: "V"
      margin: "0 4px"
      padding: "0 8px"
    - type: "binding mode"
      background: "#ffffff33"
      margin: "0 4px 0 0"
      padding: "0 8px"
    - type: "clock"
      time_formatting: "hh:mm tt  ddd  dd/MM/yyyy"

workspaces:
  # - name: "1"
  #   display_name: "Work"
  #   bind_to_monitor: 1
  #   keep_alive: false
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost|ScreenToGif|SnippingTool|mmc|WizTree64|msrdc/"

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        bindings: ["H", "Left"]
      - command: "resize width +2%"
        bindings: ["L", "Right"]
      - command: "resize height +2%"
        bindings: ["K", "Up"]
      - command: "resize height -2%"
        bindings: ["J", "Down"]
      # Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["Alt+Shift+H"]
  - command: "focus right"
    bindings: ["Alt+Shift+L"]
  - command: "focus up"
    bindings: ["Alt+Shift+K"]
  - command: "focus down"
    bindings: ["Alt+Shift+J"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["Alt+Shift+Left"]
  - command: "move right"
    bindings: ["Alt+Shift+Right"]
  - command: "move up"
    bindings: ["Alt+Shift+Up"]
  - command: "move down"
    bindings: ["Alt+Shift+Down"]

  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    binding: "Ctrl+Alt+Left"
  - command: "resize width +2%"
    binding: "Ctrl+Alt+Right"
  - command: "resize height +2%"
    binding: "Ctrl+Alt+Up"
  - command: "resize height -2%"
    binding: "Ctrl+Alt+Down"

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - command: "binding mode resize"
    binding: "Alt+R"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "Alt+V"

  # Close focused window.
  - command: "close"
    binding: "Alt+Shift+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "Alt+Shift+E"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "Alt+Shift+R"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - command: "exec 'C:/Program Files/WezTerm/wezterm-gui.exe'"
    binding: "Alt+Shift+T"

  - command: "exec 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'"
    binding: "Alt+Shift+F"

  - command: "toggle floating"
    binding: "Alt+Shift+G"

  - command: "toggle maximized"
    binding: "Alt+Shift+Z"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    bindings: ["Ctrl+Alt+J", "Ctrl+LWin+J"]
  - command: "focus workspace prev"
    bindings: ["Ctrl+Alt+K", "Ctrl+LWin+K"]

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"

  # Move focused workspace to a monitor in a given direction.
  - command: "move workspace left"
    binding: "Alt+Shift+A"
  - command: "move workspace right"
    binding: "Alt+Shift+D"
  - command: "move workspace up"
    binding: "Alt+Shift+W"
  - command: "move workspace down"
    binding: "Alt+Shift+S"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Alt+Shift+9"]
